services:
  todo_api:
    build: .
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - CLIENT_URL=${CLIENT_URL}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${API_PORT}:9090
    depends_on:
      - todo_db
    volumes:
      - ./:/app
    # command: go run ./cmd/migrate

  todo_db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - ./db-data:/var/lib/postgresql/data